services:
  serve:
    image: ollama/ollama:0.9.6
    ports:
      - "32888:11434"
    environment:
      OLLAMA_HOST: "0.0.0.0:11434"
      OLLAMA_KEEP_ALIVE: "30m"
      OLLAMA_GPU_OVERHEAD: "0"
      OLLAMA_FLASH_ATTENTION: "1"
      OLLAMA_MAX_LOADED_MODELS: "2"
      OLLAMA_MAX_QUEUE: "64"
      OLLAMA_NUM_PARALLEL: 1
      OLLAMA_NEW_ENGINE: 1
    restart: always
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: "32G"
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./ollama
        target: /root/.ollama

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "32889:8080"
    environment:
      OLLAMA_BASE_URL: "http://serve:11434"
      ENABLE_WEBSOCKET_SUPPORT: true
    volumes:
      - type: bind
        source: .open-webui
        target: /app/backend/data
    depends_on:
      - serve
