services:
  serve:
    image: ollama/ollama:0.5.4
    ports:
      - "11434:11434"
    environment:
      OLLAMA_HOST: "0.0.0.0:11434"
      OLLAMA_KEEP_ALIVE: "30m"
      OLLAMA_GPU_OVERHEAD: "0"
      OLLAMA_FLASH_ATTENTION: "1"
      OLLAMA_MAX_LOADED_MODELS: "2"
      OLLAMA_MAX_QUEUE: "64"
      OLLAMA_NUM_PARALLEL: "1"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ./ollama
        target: /root/.ollama
